"""Persona Inferer (v0.8 P1-1 — Stage1 LLM for persona recommendation + hook candidates).

Input: ASR transcript + visual keyframe descriptions (optional)
Output: Recommended persona + ≥3 hook candidates + paragraph skeleton

This module implements the Stage1 LLM call that infers which persona from
docs/personas/ best fits the source video content, and generates hook
candidates before full narrative IR generation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

# === Data Models ===


@dataclass
class HookCandidate:
    """A single hook candidate generated by Stage1 LLM."""

    text: str
    rationale: str  # Why this hook works (design intent / contradiction / detail)
    approx_source_start_sec: float = 0.0


@dataclass
class PersonaInferenceResult:
    """Output of persona_inferer.infer()."""

    recommended_persona: str  # e.g., "toxic_middle_aged"
    confidence: float  # 0.0 - 1.0
    hook_candidates: list[HookCandidate] = field(default_factory=list)
    paragraph_skeleton: list[dict[str, Any]] = field(default_factory=list)
    # paragraph_skeleton example: [{"topic": "开场冲突", "approx_start_sec": 0.0, "approx_end_sec": 15.0}, ...]


# === Prompt Templates ===

SYSTEM_PROMPT = """你是一位 B 站二创内容策略分析师，擅长从视频内容推断最适合的解说人格。

【任务】
给定 ASR 转录文本和可选的视觉关键帧描述，你需要：
1. 从 docs/personas/ 中的人格库中选择最匹配的 1 种人格
2. 生成 ≥3 个钩子候选（前 5 句内使用的强洞察句子）
3. 输出段落骨架（将视频划分为 3-5 个逻辑段落）

【人格库】
以下是可用的人格列表（详细定义见 docs/personas/*.md）：
- toxic_middle_aged（毒舌中年）：犀利讽刺，适合烂片吐槽、社会现象解读
- healing_big_sister（治愈大姐）：温暖共情，适合情感类影视、家庭剧
- archaeologist（考古学家）：学术化但接地气，适合经典电影重读、文化符号分析
- rage_brother（暴躁老哥）：直接粗粝，适合烂片吐槽、逻辑漏洞揭露
- empathy_senior（共情学姐）：温柔细腻，适合青春剧、成长故事
- sarcastic_gen_z（讽刺 Z 世代）：玩梗反讽，适合年轻化内容、套路拆解

【钩子候选要求】
每个钩子必须满足以下任一条件：
- 揭示设计意图（"导演故意..."）
- 指出矛盾（"画面说 A，声音说 B..."）
- 发现细节（"注意第 X 秒的..."）
- 吐槽/反差（"你以为...结果..."）

钩子必须是"具体观察 + 立场解读"格式，禁止空洞形容词（绝了/洗脑/拉满等）。

【段落骨架要求】
将视频划分为 3-5 个逻辑段落，每个段落包含：
- topic: 段落主题（如"开场冲突"、"角色介绍"、"高潮反转"、"结局升华"）
- approx_start_sec: 段落起始时间（秒）
- approx_end_sec: 段落结束时间（秒）

【输出格式】
严格输出 JSON，符合以下 Schema：
{
  "recommended_persona": string,
  "confidence": float,
  "hook_candidates": [
    {
      "text": string,
      "rationale": string,
      "approx_source_start_sec": float
    }
  ],
  "paragraph_skeleton": [
    {
      "topic": string,
      "approx_start_sec": float,
      "approx_end_sec": float
    }
  ]
}
"""

USER_PROMPT = """ASR 转录文本（前 2000 字符）：
{asr_preview}

视觉关键帧描述（可选，若无则忽略）：
{keyframe_descriptions}

请根据上述内容推断最适合的人格，并生成钩子候选和段落骨架。
"""


# === Core Functions ===


def infer_persona(
    asr_text: str,
    keyframe_descriptions: str = "",
    llm_client: Any = None,
) -> PersonaInferenceResult:
    """Infer recommended persona + generate hook candidates + paragraph skeleton.

    Args:
        asr_text: Full ASR transcript (will be truncated to first 2000 chars for preview).
        keyframe_descriptions: Optional visual keyframe descriptions (one per line).
        llm_client: LangChain chat model instance (e.g., ChatOpenAI for DeepSeek).
                   If None, uses default DeepSeek client from autoclip.llm.get_default_client().

    Returns:
        PersonaInferenceResult with recommended persona, hooks, and skeleton.

    Raises:
        ValueError: If LLM response is invalid JSON or missing required fields.
    """
    if llm_client is None:
        from autoclip.llm import get_default_client

        llm_client = get_default_client()

    # Truncate ASR to first 2000 chars for preview
    asr_preview = asr_text[:2000] if len(asr_text) > 2000 else asr_text

    system_message = SystemMessage(content=SYSTEM_PROMPT)
    user_message = HumanMessage(
        content=USER_PROMPT.format(
            asr_preview=asr_preview,
            keyframe_descriptions=keyframe_descriptions or "（无视觉关键帧描述）",
        )
    )

    # Call LLM
    response = llm_client.invoke([system_message, user_message])
    raw_content = response.content if hasattr(response, "content") else str(response)

    # Parse JSON
    try:
        data = json.loads(raw_content.strip())
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON in persona inferer response: {e}\nRaw: {raw_content[:500]}") from e

    # Validate required fields
    if "recommended_persona" not in data:
        raise ValueError("Missing 'recommended_persona' in response")
    if "hook_candidates" not in data or len(data["hook_candidates"]) < 3:
        raise ValueError("Must have at least 3 hook candidates")
    if "paragraph_skeleton" not in data:
        raise ValueError("Missing 'paragraph_skeleton' in response")

    # Build result
    hook_candidates = [
        HookCandidate(
            text=h["text"],
            rationale=h.get("rationale", ""),
            approx_source_start_sec=h.get("approx_source_start_sec", 0.0),
        )
        for h in data["hook_candidates"]
    ]

    return PersonaInferenceResult(
        recommended_persona=data["recommended_persona"],
        confidence=float(data.get("confidence", 0.5)),
        hook_candidates=hook_candidates,
        paragraph_skeleton=data["paragraph_skeleton"],
    )


def load_persona_description(persona_name: str) -> str:
    """Load persona description from docs/personas/{persona_name}.md.

    Args:
        persona_name: Persona filename without .md extension (e.g., "toxic_middle_aged").

    Returns:
        Full markdown content of the persona file, or empty string if file not found.
    """
    persona_path = Path(__file__).parent.parent.parent.parent / "docs" / "personas" / f"{persona_name}.md"
    if not persona_path.exists():
        return ""
    return persona_path.read_text(encoding="utf-8")
